library(here)

source(here("JHU_and_COL_subanalysis/00_setup.R"))
source(here("JHU_and_COL_subanalysis/01_helper_variables.R"))
source(here("JHU_and_COL_subanalysis/02_restructure_to_long_format.R"))
source(here("JHU_and_COL_subanalysis/03_mbms_random_effects.R"))
source(here("JHU_and_COL_subanalysis/04_mesa_random_effects.R"))
source(here("JHU_and_COL_subanalysis/05_mbms_traditional_approach.R"))
source(here("JHU_and_COL_subanalysis/06_mesa_traditional_approach.R"))
source(here("JHU_and_COL_subanalysis/07_clean_results.R"))
source(here("JHU_and_COL_subanalysis/08_plot_results.R"))